### ISSUE TITLE
Problem running example dataset

### ISSUE THREAD

**Issue by timeaeltes** [losonczylab/sima#215] opened 2016-06-07 12:42 UTC
Hi

I have just downloaded the SIMA package and tried to run your example dataset from www.losonczylab.org/workflow_data.zip.
I've got the following error:
Traceback (most recent call last):
  File "C:\Users\eltes.timea\Desktop\Sima trial\sima_trial.py", line 107, in <module>
    dataset.segment(segmentation_approach, 'auto_ROIs')
  File "C:\Python27\lib\site-packages\sima\imaging.py", line 886, in segment
    rois = strategy.segment(self)
  File "C:\Python27\lib\site-packages\sima\segment\segment.py", line 46, in segment
    rois = self._segment(dataset)
  File "C:\Python27\lib\site-packages\sima\segment\segment.py", line 88, in checked_func
    return func(self, dataset)
  File "C:\Python27\lib\site-packages\sima\segment\ca1pc.py", line 267, in _segment
    return self._normcut_method.segment(dataset)
  File "C:\Python27\lib\site-packages\sima\segment\segment.py", line 46, in segment
    rois = self._segment(dataset)
  File "C:\Python27\lib\site-packages\sima\segment\segment.py", line 88, in checked_func
    return func(self, dataset)
  File "C:\Python27\lib\site-packages\sima\segment\normcut.py", line 503, in _segment
    params['cut_min_size'], params['cut_max_size'])
  File "C:\Python27\lib\site-packages\sima\segment\normcut.py", line 223, in itercut
    cuts, penalty = cut.split()
  File "C:\Python27\lib\site-packages\sima\segment\normcut.py", line 154, in split
    C = normcut_vectors(self.affinity_matrix, 1)
  File "C:\Python27\lib\site-packages\sima\segment\normcut.py", line 67, in normcut_vectors
    which='LM')  # Get the largest eigenvalues.
  File "C:\Python27\lib\site-packages\scipy\sparse\linalg\eigen\arpack\arpack.py", line 1545, in eigsh
    symmetric=True, tol=tol)
  File "C:\Python27\lib\site-packages\scipy\sparse\linalg\eigen\arpack\arpack.py", line 1038, in get_OPinv_matvec
    return SpLuInv(A.tocsc()).matvec
  File "C:\Python27\lib\site-packages\scipy\sparse\linalg\eigen\arpack\arpack.py", line 899, in __init__
    self.M_lu = splu(M)
  File "C:\Python27\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py", line 257, in splu
    ilu=False, options=_options)
MemoryError

Any suggestions or advice you might have would be greatly appreciated.

Thanks,
Timea

**Comment by jzaremba** [comment] 2016-06-23 21:05
What is sima_trial.py? Is it our workflow.py example (https://github.com/losonczylab/sima/blob/master/examples/workflow.py)?

**Comment by timeaeltes** [comment] 2016-06-24 08:03
Yes sima_trial.py it is your workflow.py example. Exactly the one as from https://github.com/losonczylab/sima/blob/master/examples/workflow.py
Thanks

**Comment by nbdanielson** [comment] 2016-06-28 20:20
@timeaeltes are you running this with your data?  Or with our example data?  What are the specs of the computer you're running this on?

**Comment by timeaeltes** [comment] 2016-06-29 09:18
Hi, I was running it with example data provided on your website.
I tried on two PCs. Here are the specs:
1. 64 bit Windows7 Professional, 32GB RAM, CPU: Intel(R) Core (TM) i7-4790 3.6GHz
2. 64 bit Windows10, 16GB RAM (15 GB usable), CPU: AMD FX-8800P Radeon R7, 12 Compute Cores 4C+8G, 2.10GHz
I ran it with 32bit Python because some packages did not work with the 64 bit version. (I am not familiar with python yet but I got some help with the installation of packages.)
Thanks

**Comment by nbdanielson** [comment] 2016-06-30 16:44
@timeaeltes This is a bit odd -- you should certainly have enough memory with 32 GB of memory.  We don't recommend running 32-bit python in a 64-bit environment, as it's possible you don't have all of that memory available to you.

That said, we do know there is a memory leak in the segmentation code.  However, we've been able to still run the workflow.py here on a similar machine.  So it seems likely that the issue is that you're using 32-bit python instead of 64.

**Comment by nbdanielson** [comment] 2016-07-05 16:18
@timeaeltes Related to the comment above, see this issue: https://github.com/losonczylab/sima/issues/42

**Comment by timeaeltes** [comment] 2016-07-18 13:09
Thanks for your help, It is working now. I will come back if I have further questions.

**Comment by nbdanielson** [comment] 2016-07-20 16:39
Great, glad to hear.  I'm going to close this issue then.

**Closed by nbdanielson** 2016-07-20 16:39 UTC
